# Generated by Django 6.1

import django.db.models.deletion
from django.db import migrations, models


def create_general_category(apps, schema_editor):
    Category = apps.get_model("store", "Category")
    Product = apps.get_model("store", "Product")

    category, created = Category.objects.get_or_create(name="General")

    # Convert existing product category values to the new Category ID
    Product.objects.all().update(category=category.id)


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),

        migrations.RunPython(
            create_general_category,
            migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="store.category",
            ),
        ),
    ]